// @flow

export const TRANSLATE: 'TRANSLATE' = 'TRANSLATE';
export const SET_TRANSLATIONS: 'TRANSLATE.SET_TRANSLATIONS' = 'TRANSLATE.SET_TRANSLATIONS';
export const SHOW_TRANSLATION: 'TRANSLATE.SHOW_TRANSLATION' = 'TRANSLATE.SHOW_TRANSLATION';