// @flow

export const SET_INITIALIZED: 'USER.SET_INITIALIZED' = 'USER.SET_INITIALIZED';
export const SET_USER_ID: 'USER.SET_USER_ID' = 'USER.SET_USER_ID';
export const SET_USER: 'USER.SET_USER' = 'USER.SET_USER';